---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: server
  description: A heart of the Parasut. All the requests are handled by this API.
  links:
    - url: https://api.parasut.com/
      title: Parasut API
spec:
  type: swagger
  lifecycle: production
  owner: group:parasutcom
  system: system-name
  definition:
    $text: https://apidocs.parasut.com/
