---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: server
  description: A heart of the Parasut. All the requests are handled by this API.
  links:
    - url: https://api.parasut.com/
      title: Parasut API
spec:
  type: openapi
  lifecycle: production
  owner: group:parasutcom
  system: parasut-mothership
definition:
    $text: https://github.com/parasutcom/backstage-software-catalog/blob/main/swagger.yaml
    
